import { nanoid } from "@reduxjs/toolkit";

export const englishWordsC1 = [
  { word: "Abasement", definition: "humiliation; degradation" },
  { word: "Abate", definition: "reduce in intensity" },
  { word: "Aberration", definition: "deviation from the normal" },
  { word: "Abeyance", definition: "Temporary cessation or suspension" },
  { word: "abhor", definition: "hate" },
  { word: "Abjure", definition: "renounce; swear to refrain from something" },
  {
    word: "Abraded",
    definition: "worn away; eroded [abrade (v); abrasion (n)]",
  },
  {
    word: "Abrasion",
    definition:
      "1. damage to skin caused by scraping; 2. process of scraping or rubbing [abrade (v)]",
  },
  { word: "Abrasive", definition: "rough; coarse; harsh" },
  { word: "Abrogate", definition: "abolish" },
  {
    word: "Abscission",
    definition: "cutting; process causing leaves to fall off",
  },
  { word: "Absolution", definition: "Forgiveness; pardon; release" },
  { word: "Abstain", definition: "desist; go without; withdraw" },
  { word: "Abstemious", definition: "self denying; refraining from indulging" },
  { word: "Abstruse", definition: "difficult to understand; obscure" },
  { word: "abut", definition: "adjoin; border" },
  { word: "Abysmal", definition: "very deep; very bad" },
  { word: "Accolade", definition: "tribute; honor; praise" },
  {
    word: "Accretion",
    definition:
      "accumulation of matter; growth produced by adding from the outside",
  },
  { word: "Acolyte", definition: "disciple; follower or attendant" },
  { word: "Acquiesce", definition: "to agree to; give in to" },
  { word: "Acrid", definition: "sharp; pungent (used of smells and tastes)" },
  { word: "Acrophobia", definition: "Fear of heights" },
  { word: "Acuity", definition: "sharpness (mental or visual)" },
  { word: "Adamant", definition: "Hard; inflexible" },
  { word: "Admonitory", definition: "scolding [admonition (n)]" },
  { word: "Adroit", definition: "skilful" },
  { word: "Adulation", definition: "strong admiration; worship" },
  { word: "Adumbrate", definition: "outline; indicate" },
  { word: "Adversity", definition: "hardship" },
  { word: "Advocate", definition: "support" },
  { word: "Aesthetic", definition: "concerning art of beauty" },
  { word: "Affable", definition: "friendly; social; easygoing" },
  { word: "Agog", definition: "Highly excited" },
  {
    word: "Aisle",
    definition: "corridor; passageway (esp. between rows of seats)",
  },
  { word: "Alacrity", definition: "quickness; enthusiasm; eagerness" },
  { word: "Alchemy", definition: "Medieval chemistry" },
  {
    word: "Alibi",
    definition: "an excuse that shows someone was not at a crime scene",
  },
  { word: "Allay", definition: "to lessen" },
  { word: "Alleviate", definition: "make less severe" },
  {
    word: "Alleviated",
    definition: "made less severe [alleviation (n); alleviate (v)]",
  },
  { word: "Allure", definition: "1. attraction (n); 2. to attract (v)" },
  { word: "Aloof", definition: "distant; detached; cold" },
  {
    word: "Altruism",
    definition: "putting others first; being self-sacrificing",
  },
  { word: "Amalgamate", definition: "join; consolidate [amalgamation (n)]" },
  { word: "Amass", definition: "accumulate" },
  {
    word: "Ambidextrous",
    definition: "able to use both left and right hands equally well",
  },
  { word: "Ambiguity", definition: "uncertainty; vagueness" },
  { word: "ambiguous", definition: "unclear in meaning" },
  {
    word: "Ambivalence",
    definition:
      "lack of clarity; wavering; the state of having contradictory or conflicting emotional attitudes",
  },
  { word: "Ambulatory", definition: "able to walk around" },
  { word: "Ameliorate", definition: "make better" },
  { word: "Amelioration", definition: "improvement" },
  { word: "Amiable", definition: "friendly" },
  { word: "Amity", definition: "friendship" },
  { word: "Amorphous", definition: "lacking in shape" },
  { word: "Amortize", definition: "pay off a debt in installments" },
  {
    word: "Anachronistic",
    definition: "occurring in the wrong time period [anachronism (n)]",
  },
  { word: "Analgesic", definition: "medicine to combat pain" },
  { word: "Analogous", definition: "comparable" },
  {
    word: "Analogue",
    definition:
      "1. something similar; 2. output proportional to input (engineering)",
  },
  { word: "Anarchy", definition: "chaos; lack of government" },
  { word: "Anecdote", definition: "a brief amusing story" },
  { word: "Animosity", definition: "hatred; antagonism" },
  { word: "Annex (v)", definition: "take possession of; seize; capture" },
  {
    word: "Annex",
    definition: "a building which is an addition to an existing building",
  },
  {
    word: "Anodized",
    definition: "electroplated; coated with thin layer of metal",
  },
  {
    word: "Anomaly",
    definition: "something which does not fit in a pattern; irregularity",
  },
  { word: "Antagonism", definition: "hostility; strong opposition" },
  { word: "Antagonistic", definition: "opposed; hostile; aggressive" },
  {
    word: "Antediluvian",
    definition: "outdated; prehistoric; very old-fashioned",
  },
  {
    word: "Anthology",
    definition: "a book which is a collection of poems or stories",
  },
  {
    word: "Anthropocentrism",
    definition: "putting man at the center of one's philosophy",
  },
  { word: "Antipathy", definition: "hatred" },
  { word: "Antiquated", definition: "outdated; old fashioned" },
  { word: "Apathetic", definition: "indifferent; uninterested; lethargic" },
  { word: "Apathy", definition: "lack of interest or emotion" },
  {
    word: "Aphoristic",
    definition: "expressed tersely [aphorism (n) = short statement; maxim]",
  },
  { word: "Apocryphal", definition: "untrue; made up" },
  {
    word: "Apostrophe",
    definition:
      "1. punctuation mark; 2. appeal to someone not present (a figure of speech)",
  },
  { word: "Appease", definition: "pacify; soothe; calm down; make peace with" },
  { word: "Apposite", definition: "fitting; suitable" },
  {
    word: "Apprehension",
    definition: "slight fear; sense of something unfavorable",
  },
  { word: "Apprehensive", definition: "worried; fearful" },
  { word: "Approbation", definition: "approval [opp. disapprobation]" },
  { word: "Arable", definition: "can be cultivated" },
  { word: "Arbitrary", definition: "random; for no definite reason" },
  {
    word: "Arbitrator",
    definition: "mediator; person appointed to judge a dispute [arbitrate (v)]",
  },
  { word: "Arboreal", definition: "living in trees; concerned with trees" },
  { word: "Arcane", definition: "obscure; known only to a few people" },
  { word: "Archaic", definition: "ancient; outdated; old fashioned" },
  {
    word: "Archetype",
    definition: "prototype; primitive pattern; classic example of",
  },
  {
    word: "Archives",
    definition: "collections of old records; place of storage of old documents",
  },
  { word: "arduous", definition: "hard" },
  { word: "Armada", definition: "fleet of ships" },
  { word: "Arresting", definition: "attracting attention; striking" },
  { word: "Arson", definition: "deliberate, criminal starting of fires" },
  { word: "Articulate", definition: "clear; lucid; eloquent" },
  { word: "Artifice", definition: "deception; trickery" },
  { word: "Artisan", definition: "craftsman" },
  { word: "Artless", definition: "without effort; without trickery; simple" },
  { word: "Ascetic", definition: "without luxuries; severely simple" },
  { word: "Asperity", definition: "using harsh or critical tone [Aspertion]" },
  { word: "Assay", definition: "1. try; 2. assess purity" },
  { word: "Assiduous", definition: "thorough; diligent" },
  { word: "Assuage", definition: "to calm" },
  { word: "Astute", definition: "perceptive; sharp-witted" },
  { word: "Asylum", definition: "place of refuge or safety" },
  {
    word: "Atavism",
    definition: "A reappearance of an earlier characteristic",
  },
  { word: "Atheist", definition: "person who does not believe in God" },
  {
    word: "Atonement",
    definition: "making amends for sin or crime [atone (v)]",
  },
  { word: "Atrophy", definition: "waste away from lack of use" },
  { word: "Attenuate", definition: "Make thin; weaken" },
  { word: "Augment", definition: "increase; make bigger" },
  { word: "Augury", definition: "prediction, looking for omens [auger (v)]" },
  { word: "Auspicious", definition: "favorable; promising to turn out well" },
  { word: "Austere", definition: "severely plain" },
  { word: "avaricious", definition: "greedy for money" },
  { word: "Aver", definition: "affirm; verify" },
  { word: "Aversion", definition: "Firm dislike" },
  { word: "Baleful", definition: "evil" },
  { word: "Balk", definition: "hinder and prevent; hesitate over" },
  {
    word: "Balm",
    definition: "soothing ointment or anything soothing [balmy (a)]",
  },
  { word: "Banal", definition: "common; dull" },
  { word: "Banality", definition: "ordinariness; dullness" },
  { word: "Bane", definition: "troublesome influence; curse" },
  { word: "bard", definition: "poet" },
  {
    word: "Barrage",
    definition:
      "extended gunfire to cover an attack; dam across river; deluge of information etc.",
  },
  { word: "Bastion", definition: "fortress; stronghold" },
  { word: "Befuddle", definition: "confuse" },
  { word: "Begrudge", definition: "resent" },
  { word: "Beguile", definition: "mislead; lure" },
  {
    word: "Belabor",
    definition: "explain in unnecessary detail; To work at or to absurd length",
  },
  { word: "Beleaguer", definition: "besiege; attack" },
  { word: "Belie", definition: "contradict; give a false impression" },
  { word: "Belittle", definition: "to demean" },
  { word: "Bellicose", definition: "war-like; aggressive" },
  { word: "Belligerent", definition: "aggressive; ready to fight" },
  { word: "Bemoan", definition: "lament; Regret strongly" },
  { word: "Benevolent", definition: "kindly" },
  { word: "Benign", definition: "kindly; harmless" },
  { word: "Benignity", definition: "compassion; gentleness; fondness" },
  { word: "Bent (n)", definition: "inclination; aptitude" },
  {
    word: "Bequeath",
    definition: "leave something in one's will to be given after one's death",
  },
  { word: "Berate", definition: "scold; criticize" },
  { word: "Beret", definition: "type of cap" },
  { word: "Bestial", definition: "behaving like a beast; brutal" },
  { word: "bigot", definition: "narrow-minded, prejudiced person" },
  { word: "Bilk", definition: "cheat; defraud" },
  { word: "Billowing", definition: "Swelling; fluttering; waving" },
  {
    word: "Blandishment",
    definition: "words used to coax or flatter [blandish (v)]",
  },
  {
    word: "Blasphemy",
    definition: "speech which offends religious sentiments",
  },
  { word: "Blatant", definition: "obvious" },
  { word: "Blighted", definition: "damaged; destroyed; ruined" },
  { word: "Blithe", definition: "free-spirited; carefree" },
  { word: "Blowhard", definition: "boastful person" },
  {
    word: "Blunderbuss",
    definition: "ancient weapon (type of gun); a clumsy person",
  },
  { word: "Bolster", definition: "support; prop up; reinforce" },
  { word: "Bombast", definition: "arrogant, pompous language" },
  { word: "Boor", definition: "ill-mannered person [boorish (a)]" },
  { word: "Boorish", definition: "ill-mannered" },
  { word: "bourgeois", definition: "middle class" },
  { word: "Boycott", definition: "refuse to have dealings with" },
  { word: "Braggart", definition: "someone who boasts" },
  { word: "Brawny", definition: "muscular" },
  { word: "Brevity", definition: "being brief" },
  {
    word: "Bristle",
    definition: "to show irritation; React in an offended or angry manner",
  },
  { word: "Broach", definition: "start to discuss; approach" },
  { word: "Brook", definition: "small stream; 2. tolerate" },
  { word: "Brusque", definition: "blunt; abrupt" },
  { word: "Bulwark", definition: "fortification; barricade; wall" },
  { word: "Bureaucracy", definition: "officialdom" },
  { word: "Burgeon", definition: "grow; flourish" },
  { word: "Burlesque", definition: "comic play; 2. lampoon" },
  { word: "burnish", definition: "polish" },
  { word: "Buttress", definition: "strengthen; support" },
  {
    word: "Byline",
    definition: "the line that tells your who wrote an article",
  },
  { word: "Cacophony", definition: "discordant loud noises" },
  { word: "Cadge", definition: "get by begging" },
  { word: "Cajole", definition: "coax" },
  { word: "Caldron", definition: "huge cooking pot" },
  { word: "Calibrate", definition: "mark an accurate scale on a device" },
  { word: "callow", definition: "immature" },
  { word: "Candid", definition: "frank; honest" },
  { word: "Candor", definition: "frankness; openness" },
  {
    word: "Canonical",
    definition: "orthodox [canon (n) = set of accepted works]",
  },
  { word: "Cant", definition: "insincere talk" },
  { word: "Cantankerous", definition: "bad-tempered; quarrelsome" },
  { word: "Capacious", definition: "spacious" },
  { word: "Capitulate", definition: "surrender; give in to" },
  { word: "Caprices", definition: "whimsies; fancies" },
  {
    word: "Cardinal",
    definition: "high ranking church official; 2. major, important",
  },
  { word: "Caret", definition: "punctuation mark signifying omission" },
  {
    word: "Caricature",
    definition: "ridicule (v); cartoon intended to ridicule (n)",
  },
  { word: "Carping", definition: "constant criticism; fault-finding" },
  { word: "Carrion", definition: "dead flesh; carcasses" },
  { word: "Cartographer", definition: "person who makes maps" },
  { word: "Castigate", definition: "scold strongly" },
  { word: "Cataclysmic", definition: "Severely destructive" },
  {
    word: "Catharsis",
    definition: "purging or cleansing of any passage of the body",
  },
  { word: "Caucus", definition: "type of private political meeting" },
  {
    word: "Caulk",
    definition: "treat with substance such as tar tomake watertight",
  },
  { word: "Cavalcade", definition: "procession of vehicles" },
  {
    word: "Cavalier",
    definition: "casual; carefree and nonchalant; arrogant disregard",
  },
  { word: "Cavil", definition: "find fault unnecessarily" },
  { word: "Celestial", definition: "concerning the sky or heavens; spiritual" },
  { word: "Censure", definition: "blame; criticize" },
  { word: "Centrifugal", definition: "moving away from a center" },
  { word: "Centripetal", definition: "moving or directed toward a center" },
  { word: "Cerebral", definition: "intellectual" },
  { word: "Chafe", definition: "become irritated by rubbing" },
  { word: "Chaff", definition: "worthless matter" },
  { word: "Chagrin", definition: "embarrassment; a complete loss of courage" },
  {
    word: "Chameleon",
    definition: "lizard that changes color in different situations",
  },
  { word: "Chicanery", definition: "trickery" },
  { word: "Chisel", definition: "steel tool for shaping materials" },
  { word: "Churlish", definition: "rude; boorish" },
  { word: "Circuitous", definition: "indirect; roundabout" },
  { word: "Circumspect", definition: "cautious" },
  { word: "Circumvent", definition: "avoid" },
  { word: "Civility", definition: "politeness" },
  {
    word: "Clairvoyant",
    definition:
      "psychic; mystic; person who claims to have supernatural ability to perceive events in the future",
  },
  { word: "Clamor", definition: "shout; scream" },
  { word: "Clandestine", definition: "secret" },
  {
    word: "Clarion",
    definition:
      "shrill, trumpetlike sound; kind of trumpet used in former times",
  },
  {
    word: "Cleave",
    definition: "split or sever; cling to; remain faithful to [adhere (v)]",
  },
  { word: "Clemency", definition: "mercy" },
  { word: "Cliche", definition: "overused expression or idea" },
  { word: "Coalesce", definition: "come together; merge" },
  { word: "Coda", definition: "passage that completes a piece of music" },
  { word: "Codify", definition: "arrange (laws, rules) as a code; classify" },
  { word: "Coerce", definition: "force" },
  { word: "Cogent", definition: "powerful; convincing" },
  { word: "Cognizant", definition: "aware; conscious" },
  { word: "Coherent", definition: "logically consistent; intelligible" },
  { word: "Colloquial", definition: "conversational; informal in language" },
  { word: "Collusion", definition: "conspiracy; secret cooperation" },
  { word: "Comely", definition: "attractive" },
  { word: "Comity", definition: "courtesy; civility" },
  { word: "Commensurate", definition: "proportional" },
  { word: "Complacent", definition: "self-satisfied" },
  {
    word: "Complaisant",
    definition: "trying to please; overly polite; obliging",
  },
  {
    word: "Complement",
    definition: "something that completes or makes up a whole",
  },
  {
    word: "Compliance",
    definition: "conformity in fulfilling requirements; readiness to yield",
  },
  { word: "Complicity", definition: "participation; involvement" },
  { word: "Comprehensive", definition: "covering or including everything" },
  { word: "Comprise", definition: "include; consist of" },
  { word: "Compunction", definition: "uneasiness caused by guilt" },
  { word: "Concatenate", definition: "link together" },
  { word: "Conceal", definition: "hide" },
  { word: "Concede", definition: "admit; yield" },
  { word: "Conceit", definition: "overblown self-esteem; a fanciful idea" },
  { word: "Conciliatory", definition: "overcoming distrust or hostility" },
  { word: "Conclusive", definition: "putting an end to doubt; convincing" },
  {
    word: "Blandishment",
    definition: "words used to coax or flatter [blandish (v)]",
  },
  {
    word: "Blasphemy",
    definition: "speech which offends religious sentiments",
  },
  { word: "Blatant", definition: "obvious" },
  { word: "Blighted", definition: "damaged; destroyed; ruined" },
  { word: "Blithe", definition: "free-spirited; carefree" },
  { word: "Blowhard", definition: "boastful person" },
  {
    word: "Blunderbuss",
    definition: "ancient weapon (type of gun); a clumsy person",
  },
  { word: "Bolster", definition: "support; prop up; reinforce" },
  { word: "Bombast", definition: "arrogant, pompous language" },
  { word: "Boor", definition: "ill-mannered person [boorish (a)]" },
  { word: "Boorish", definition: "ill-mannered" },
  { word: "bourgeois", definition: "middle class" },
  { word: "Boycott", definition: "refuse to have dealings with" },
  { word: "Braggart", definition: "someone who boasts" },
  { word: "Brawny", definition: "muscular" },
  { word: "Brevity", definition: "being brief" },
  {
    word: "Bristle",
    definition: "to show irritation; React in an offended or angry manner",
  },
  { word: "Broach", definition: "start to discuss; approach" },
  { word: "Brook", definition: "small stream; 2. tolerate" },
  { word: "Brusque", definition: "blunt; abrupt" },
  { word: "Bulwark", definition: "fortification; barricade; wall" },
  { word: "Bureaucracy", definition: "officialdom" },
  { word: "Burgeon", definition: "grow; flourish" },
  { word: "Burlesque", definition: "comic play; 2. lampoon" },
  { word: "burnish", definition: "polish" },
  { word: "Buttress", definition: "strengthen; support" },
  {
    word: "Byline",
    definition: "the line that tells your who wrote an article",
  },
  { word: "Cacophony", definition: "discordant loud noises" },
  { word: "Cadge", definition: "get by begging" },
  { word: "Cajole", definition: "coax" },
  { word: "Caldron", definition: "huge cooking pot" },
  { word: "Calibrate", definition: "mark an accurate scale on a device" },
  { word: "callow", definition: "immature" },
  { word: "Candid", definition: "frank; honest" },
  { word: "Candor", definition: "frankness; openness" },
  {
    word: "Canonical",
    definition: "orthodox [canon (n) = set of accepted works]",
  },
  { word: "Cant", definition: "insincere talk" },
  { word: "Cantankerous", definition: "bad-tempered; quarrelsome" },
  { word: "Capacious", definition: "spacious" },
  { word: "Capitulate", definition: "surrender; give in to" },
  { word: "Caprices", definition: "whimsies; fancies" },
  {
    word: "Cardinal",
    definition: "high ranking church official; 2. major, important",
  },
  { word: "Caret", definition: "punctuation mark signifying omission" },
  {
    word: "Caricature",
    definition: "ridicule (v); cartoon intended to ridicule (n)",
  },
  { word: "Carping", definition: "constant criticism; fault-finding" },
  { word: "Carrion", definition: "dead flesh; carcasses" },
  { word: "Cartographer", definition: "person who makes maps" },
  { word: "Castigate", definition: "scold strongly" },
  { word: "Cataclysmic", definition: "Severely destructive" },
  {
    word: "Catharsis",
    definition: "purging or cleansing of any passage of the body",
  },
  { word: "Caucus", definition: "type of private political meeting" },
  {
    word: "Caulk",
    definition: "treat with substance such as tar tomake watertight",
  },
  { word: "Cavalcade", definition: "procession of vehicles" },
  {
    word: "Cavalier",
    definition: "casual; carefree and nonchalant; arrogant disregard",
  },
  { word: "Cavil", definition: "find fault unnecessarily" },
  { word: "Celestial", definition: "concerning the sky or heavens; spiritual" },
  { word: "Censure", definition: "blame; criticize" },
  { word: "Centrifugal", definition: "moving away from a center" },
  { word: "Centripetal", definition: "moving or directed toward a center" },
  { word: "Cerebral", definition: "intellectual" },
  { word: "Chafe", definition: "become irritated by rubbing" },
  { word: "Chaff", definition: "worthless matter" },
  { word: "Chagrin", definition: "embarrassment; a complete loss of courage" },
  {
    word: "Chameleon",
    definition: "lizard that changes color in different situations",
  },
  { word: "Chicanery", definition: "trickery" },
  { word: "Chisel", definition: "steel tool for shaping materials" },
  { word: "Churlish", definition: "rude; boorish" },
  { word: "Circuitous", definition: "indirect; roundabout" },
  { word: "Circumspect", definition: "cautious" },
  { word: "Circumvent", definition: "avoid" },
  { word: "Civility", definition: "politeness" },
  {
    word: "Clairvoyant",
    definition:
      "psychic; mystic; person who claims to have supernatural ability to perceive events in the future",
  },
  { word: "Clamor", definition: "shout; scream" },
  { word: "Clandestine", definition: "secret" },
  {
    word: "Clarion",
    definition:
      "shrill, trumpetlike sound; kind of trumpet used in former times",
  },
  {
    word: "Cleave",
    definition: "split or sever; cling to; remain faithful to [adhere (v)]",
  },
  { word: "Clemency", definition: "mercy" },
  { word: "Cliche", definition: "overused expression or idea" },
  { word: "Coalesce", definition: "come together; merge" },
  { word: "Coda", definition: "passage that completes a piece of music" },
  { word: "Codify", definition: "arrange (laws, rules) as a code; classify" },
  { word: "Coerce", definition: "force" },
  { word: "Cogent", definition: "powerful; convincing" },
  { word: "Cognizant", definition: "aware; conscious" },
  { word: "Coherent", definition: "logically consistent; intelligible" },
  { word: "Colloquial", definition: "conversational; informal in language" },
  { word: "Collusion", definition: "conspiracy; secret cooperation" },
  { word: "Comely", definition: "attractive" },
  { word: "Comity", definition: "courtesy; civility" },
  { word: "Commensurate", definition: "proportional" },
  { word: "Complacent", definition: "self-satisfied" },
  {
    word: "Complaisant",
    definition: "trying to please; overly polite; obliging",
  },
  {
    word: "Complement",
    definition: "something that completes or makes up a whole",
  },
  {
    word: "Compliance",
    definition: "conformity in fulfilling requirements; readiness to yield",
  },
  { word: "Complicity", definition: "participation; involvement" },
  { word: "Comprehensive", definition: "covering or including everything" },
  { word: "Comprise", definition: "include; consist of" },
  { word: "Compunction", definition: "uneasiness caused by guilt" },
  { word: "Concatenate", definition: "link together" },
  { word: "Conceal", definition: "hide" },
  { word: "Concede", definition: "admit; yield" },
  { word: "Conceit", definition: "overblown self-esteem; a fanciful idea" },
  { word: "Conciliatory", definition: "overcoming distrust or hostility" },
  { word: "Conclusive", definition: "putting an end to doubt; convincing" },
];

const array = englishWordsC1.map((w) => ({ id: nanoid(8), ...w }));

console.log(array, "arr");

console.log(englishWordsC1);
